<?php

/**
 * BaseInstructorCourse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $course_id
 * @property string $access
 * @property sfGuardUser $User
 * @property Course $Course
 * @property Doctrine_Collection $sfGuardUser
 * 
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method integer             getCourseId()    Returns the current record's "course_id" value
 * @method string              getAccess()      Returns the current record's "access" value
 * @method sfGuardUser         getUser()        Returns the current record's "User" value
 * @method Course              getCourse()      Returns the current record's "Course" value
 * @method Doctrine_Collection getSfGuardUser() Returns the current record's "sfGuardUser" collection
 * @method InstructorCourse    setUserId()      Sets the current record's "user_id" value
 * @method InstructorCourse    setCourseId()    Sets the current record's "course_id" value
 * @method InstructorCourse    setAccess()      Sets the current record's "access" value
 * @method InstructorCourse    setUser()        Sets the current record's "User" value
 * @method InstructorCourse    setCourse()      Sets the current record's "Course" value
 * @method InstructorCourse    setSfGuardUser() Sets the current record's "sfGuardUser" collection
 * 
 * @package    Wikigrads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInstructorCourse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('instructor_course');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('course_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('access', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Course', array(
             'local' => 'course_id',
             'foreign' => 'id'));

        $this->hasMany('sfGuardUser', array(
             'refClass' => 'InstructorCourse',
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}