<?php

/**
 * BaseSchool
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $short_school
 * @property string $twitter_list
 * @property integer $first_friend_id
 * @property string $default_user_image
 * @property string $timezone
 * @property integer $is_lms
 * @property string $lms_domain
 * @property sfGuardUser $FirstFriend
 * @property Doctrine_Collection $UserSchool
 * @property Doctrine_Collection $Department
 * 
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getShortSchool()        Returns the current record's "short_school" value
 * @method string              getTwitterList()        Returns the current record's "twitter_list" value
 * @method integer             getFirstFriendId()      Returns the current record's "first_friend_id" value
 * @method string              getDefaultUserImage()   Returns the current record's "default_user_image" value
 * @method string              getTimezone()           Returns the current record's "timezone" value
 * @method integer             getIsLms()              Returns the current record's "is_lms" value
 * @method string              getLmsDomain()          Returns the current record's "lms_domain" value
 * @method sfGuardUser         getFirstFriend()        Returns the current record's "FirstFriend" value
 * @method Doctrine_Collection getUserSchool()         Returns the current record's "UserSchool" collection
 * @method Doctrine_Collection getDepartment()         Returns the current record's "Department" collection
 * @method School              setName()               Sets the current record's "name" value
 * @method School              setShortSchool()        Sets the current record's "short_school" value
 * @method School              setTwitterList()        Sets the current record's "twitter_list" value
 * @method School              setFirstFriendId()      Sets the current record's "first_friend_id" value
 * @method School              setDefaultUserImage()   Sets the current record's "default_user_image" value
 * @method School              setTimezone()           Sets the current record's "timezone" value
 * @method School              setIsLms()              Sets the current record's "is_lms" value
 * @method School              setLmsDomain()          Sets the current record's "lms_domain" value
 * @method School              setFirstFriend()        Sets the current record's "FirstFriend" value
 * @method School              setUserSchool()         Sets the current record's "UserSchool" collection
 * @method School              setDepartment()         Sets the current record's "Department" collection
 * 
 * @package    Wikigrads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSchool extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('school');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('short_school', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('twitter_list', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('first_friend_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('default_user_image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('timezone', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_lms', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 1,
             ));
        $this->hasColumn('lms_domain', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as FirstFriend', array(
             'local' => 'first_friend_id',
             'foreign' => 'id'));

        $this->hasMany('UserSchool', array(
             'local' => 'id',
             'foreign' => 'school_id'));

        $this->hasMany('Department', array(
             'local' => 'id',
             'foreign' => 'school_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($sluggable0);
    }
}