<?php

/**
 * BaseDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $course_id
 * @property integer $user_id
 * @property string $file
 * @property string $name
 * @property clob $description
 * @property timestamp $date
 * @property Course $Course
 * @property sfGuardUser $User
 * 
 * @method integer     getCourseId()    Returns the current record's "course_id" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method string      getFile()        Returns the current record's "file" value
 * @method string      getName()        Returns the current record's "name" value
 * @method clob        getDescription() Returns the current record's "description" value
 * @method timestamp   getDate()        Returns the current record's "date" value
 * @method Course      getCourse()      Returns the current record's "Course" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method Document    setCourseId()    Sets the current record's "course_id" value
 * @method Document    setUserId()      Sets the current record's "user_id" value
 * @method Document    setFile()        Sets the current record's "file" value
 * @method Document    setName()        Sets the current record's "name" value
 * @method Document    setDescription() Sets the current record's "description" value
 * @method Document    setDate()        Sets the current record's "date" value
 * @method Document    setCourse()      Sets the current record's "Course" value
 * @method Document    setUser()        Sets the current record's "User" value
 * 
 * @package    Wikigrads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocument extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('document');
        $this->hasColumn('course_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Course', array(
             'local' => 'course_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}