<?php

/**
 * BaseSubject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Course
 * @property Doctrine_Collection $UserSubject
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method Doctrine_Collection getCourse()      Returns the current record's "Course" collection
 * @method Doctrine_Collection getUserSubject() Returns the current record's "UserSubject" collection
 * @method Subject             setName()        Sets the current record's "name" value
 * @method Subject             setCourse()      Sets the current record's "Course" collection
 * @method Subject             setUserSubject() Sets the current record's "UserSubject" collection
 * 
 * @package    Wikigrads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subject');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Course', array(
             'local' => 'id',
             'foreign' => 'subject_id'));

        $this->hasMany('UserSubject', array(
             'local' => 'id',
             'foreign' => 'subject_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}