<?php

/**
 * BaseCourseGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Course
 * 
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getCourse() Returns the current record's "Course" collection
 * @method CourseGroup         setName()   Sets the current record's "name" value
 * @method CourseGroup         setCourse() Sets the current record's "Course" collection
 * 
 * @package    Wikigrads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourseGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course_group');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Course', array(
             'local' => 'id',
             'foreign' => 'course_group_id'));

        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($softdelete0);
    }
}