<?php

/**
 * BaseAcademicTermCourse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $academic_term_id
 * @property integer $course_id
 * @property AcademicTerm $AcademicTerm
 * @property Course $Course
 * 
 * @method integer            getAcademicTermId()   Returns the current record's "academic_term_id" value
 * @method integer            getCourseId()         Returns the current record's "course_id" value
 * @method AcademicTerm       getAcademicTerm()     Returns the current record's "AcademicTerm" value
 * @method Course             getCourse()           Returns the current record's "Course" value
 * @method AcademicTermCourse setAcademicTermId()   Sets the current record's "academic_term_id" value
 * @method AcademicTermCourse setCourseId()         Sets the current record's "course_id" value
 * @method AcademicTermCourse setAcademicTerm()     Sets the current record's "AcademicTerm" value
 * @method AcademicTermCourse setCourse()           Sets the current record's "Course" value
 * 
 * @package    Wikigrads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcademicTermCourse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('academic_term_course');
        $this->hasColumn('academic_term_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('course_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AcademicTerm', array(
             'local' => 'academic_term_id',
             'foreign' => 'id'));

        $this->hasOne('Course', array(
             'local' => 'course_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}