<?php

/**
 * BaseUserAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $file
 * @property string $url
 * @property string $name
 * @property sfGuardUser $User
 * @property Doctrine_Collection $Post
 * 
 * @method integer             getUserId()  Returns the current record's "user_id" value
 * @method string              getFile()    Returns the current record's "file" value
 * @method string              getUrl()     Returns the current record's "url" value
 * @method string              getName()    Returns the current record's "name" value
 * @method sfGuardUser         getUser()    Returns the current record's "User" value
 * @method Doctrine_Collection getPost()    Returns the current record's "Post" collection
 * @method UserAttachment      setUserId()  Sets the current record's "user_id" value
 * @method UserAttachment      setFile()    Sets the current record's "file" value
 * @method UserAttachment      setUrl()     Sets the current record's "url" value
 * @method UserAttachment      setName()    Sets the current record's "name" value
 * @method UserAttachment      setUser()    Sets the current record's "User" value
 * @method UserAttachment      setPost()    Sets the current record's "Post" collection
 * 
 * @package    Wikigrads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_attachment');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Post', array(
             'local' => 'id',
             'foreign' => 'user_attachment_id'));
    }
}