<?php

/**
 * BaseDepartment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $school_id
 * @property string $name
 * @property string $alias
 * @property integer $sort
 * @property School $School
 * @property Doctrine_Collection $UserSchool
 * @property Doctrine_Collection $Course
 * 
 * @method integer             getSchoolId()   Returns the current record's "school_id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getAlias()      Returns the current record's "alias" value
 * @method integer             getSort()       Returns the current record's "sort" value
 * @method School              getSchool()     Returns the current record's "School" value
 * @method Doctrine_Collection getUserSchool() Returns the current record's "UserSchool" collection
 * @method Doctrine_Collection getCourse()     Returns the current record's "Course" collection
 * @method Department          setSchoolId()   Sets the current record's "school_id" value
 * @method Department          setName()       Sets the current record's "name" value
 * @method Department          setAlias()      Sets the current record's "alias" value
 * @method Department          setSort()       Sets the current record's "sort" value
 * @method Department          setSchool()     Sets the current record's "School" value
 * @method Department          setUserSchool() Sets the current record's "UserSchool" collection
 * @method Department          setCourse()     Sets the current record's "Course" collection
 * 
 * @package    Wikigrads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('department');
        $this->hasColumn('school_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('alias', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('sort', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('School', array(
             'local' => 'school_id',
             'foreign' => 'id'));

        $this->hasMany('UserSchool', array(
             'local' => 'id',
             'foreign' => 'primary_department_id'));

        $this->hasMany('Course', array(
             'local' => 'id',
             'foreign' => 'department_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}