<?php

/**
 * BaseUserLike
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $object_id
 * @property integer $count_like
 * 
 * @method integer  getUserId()     Returns the current record's "user_id" value
 * @method integer  getObjectId()   Returns the current record's "object_id" value
 * @method integer  getCountLike()  Returns the current record's "count_like" value
 * @method UserLike setUserId()     Sets the current record's "user_id" value
 * @method UserLike setObjectId()   Sets the current record's "object_id" value
 * @method UserLike setCountLike()  Sets the current record's "count_like" value
 * 
 * @package    Wikigrads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserLike extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_like');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('count_like', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}