<?php

/**
 * BaseAcademicTerm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property enum $term
 * @property integer $year
 * @property boolean $is_active
 * @property Doctrine_Collection $AcademicTermCourse
 * 
 * @method enum                getTerm()               Returns the current record's "term" value
 * @method integer             getYear()               Returns the current record's "year" value
 * @method boolean             getIsActive()           Returns the current record's "is_active" value
 * @method Doctrine_Collection getAcademicTermCourse() Returns the current record's "AcademicTermCourse" collection
 * @method AcademicTerm        setTerm()               Sets the current record's "term" value
 * @method AcademicTerm        setYear()               Sets the current record's "year" value
 * @method AcademicTerm        setIsActive()           Sets the current record's "is_active" value
 * @method AcademicTerm        setAcademicTermCourse() Sets the current record's "AcademicTermCourse" collection
 * 
 * @package    Wikigrads
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAcademicTerm extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('academic_term');
        $this->hasColumn('term', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Spring',
              1 => 'Summer',
              2 => 'Fall',
              3 => 'Winter',
             ),
             ));
        $this->hasColumn('year', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AcademicTermCourse', array(
             'local' => 'id',
             'foreign' => 'academic_term_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}