sf_guard_user_group:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUserGroup
    module:               sfGuardUserGroup
    prefix_path:          /sfGuardUserGroup
    column:               id
    with_wildcard_routes: true

instructorcourse:
  class: sfDoctrineRouteCollection
  options:
    model:                instructorcourse
    module:               instructorcourse
    prefix_path:          /instructorcourse
    column:               id
    with_wildcard_routes: true

user_school:
  class: sfDoctrineRouteCollection
  options:
    model:                UserSchool
    module:               user_school
    prefix_path:          /user_school
    column:               id
    with_wildcard_routes: true

academic_term_academic_term:
  class: sfDoctrineRouteCollection
  options:
    model:                AcademicTerm
    module:               academic_term
    prefix_path:          /academic_term
    column:               id
    with_wildcard_routes: true

document_document:
  class: sfDoctrineRouteCollection
  options:
    model:                Document
    module:               document
    prefix_path:          /document
    column:               id
    with_wildcard_routes: true

department_department:
  class: sfDoctrineRouteCollection
  options:
    model:                Department
    module:               department
    prefix_path:          /department
    column:               id
    with_wildcard_routes: true

course_course:
  class: sfDoctrineRouteCollection
  options:
    model:                Course
    module:               course
    prefix_path:          /course
    column:               id
    with_wildcard_routes: true

event_event:
  class: sfDoctrineRouteCollection
  options:
    model:                Event
    module:               event
    prefix_path:          /event
    column:               id
    with_wildcard_routes: true

school_school:
  class: sfDoctrineRouteCollection
  options:
    model:                School
    module:               school
    prefix_path:          /school
    column:               id
    with_wildcard_routes: true

document:
  class: sfDoctrineRouteCollection
  options:
    model:                document
    module:               document
    prefix_path:          /document
    column:               id
    with_wildcard_routes: true

event:
  class: sfDoctrineRouteCollection
  options:
    model:                event
    module:               event
    prefix_path:          /event
    column:               id
    with_wildcard_routes: true

subject:
  class: sfDoctrineRouteCollection
  options:
    model:                subject
    module:               subject
    prefix_path:          /subject
    column:               id
    with_wildcard_routes: true

department:
  class: sfDoctrineRouteCollection
  options:
    model:                department
    module:               department
    prefix_path:          /department
    column:               id
    with_wildcard_routes: true

course:
  class: sfDoctrineRouteCollection
  options:
    model:                course
    module:               course
    prefix_path:          /course
    column:               id
    with_wildcard_routes: true

InstructorCourse:
  class: sfDoctrineRouteCollection
  options:
    model:                instructorcourse
    module:               instructorcourse
    prefix_path:          /instructorcourse
    column:               id
    with_wildcard_routes: true

academic_term:
  class: sfDoctrineRouteCollection
  options:
    model:                academicTerm
    module:               academic_term
    prefix_path:          /academic_term
    column:               id
    with_wildcard_routes: true

sf_guard_user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               sf_guard_user
    prefix_path:          /sf_guard_user
    column:               id
    with_wildcard_routes: true

school:
  class: sfDoctrineRouteCollection
  options:
    model:                school
    module:               school
    prefix_path:          /school
    column:               id
    with_wildcard_routes: true

sfGuardUserProfile:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUserProfile
    module:               sfGuardUserProfile
    prefix_path:          sfGuardUserProfile
    column:               id
    with_wildcard_routes: true
#    module:               sfGuardUserProfile
#    prefix_path:          /sf_guard_user_profile

LMSDomainKeySecret:
  class: sfDoctrineRouteCollection
  options:
    model:                LMSDomainKeySecret
    module:               LMSDomainKeySecret
    prefix_path:          /LMSDomainKeySecret
    column:               id
    with_wildcard_routes: true


# course import

course_import:
  url: /course-import
  param: { module: course, action: import }

course_filter:
  url: /coursefilter
  param: { module: course, action: coursefilter }

autocomplite:
  url: /autocomplite/:type
  param: { module: main, action: autocomplite }

autotextcomplite:
  url: /autotextcomplite/:table
  param: { module: main, action: autotextcomplite }

checkobject:
  url: /checkobject
  param: { module: main, action: checkobject }

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# sfDoctrineGuardPlugin

document_download:
  url: /download-document/:slug
  param: {module: document, action: download}

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

# default rules
homepage:
  url:   /
  param: { module: main, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
