generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUserProfile
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sfGuardUserProfile
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display:
          - id
          - user
          - email
          - fullname
          - birthday
          - activity
          - is_staff
          - created_at
          - updated_at
          - deleted_at
          
      filter:
        display:
          - user_id
          - email
          - fullname
          - birthday
          - activity
          - is_staff
          - created_at
          - updated_at
          - deleted_at
      form: 
        class: AdminSfGuardUserProfile
      edit:    ~
      new:     ~
