<?php

/**
 * AcademicTermCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AcademicTermCourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AcademicTermCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AcademicTermCourse');
    }
}