<?php

/**
 * Course
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sf_sandbox_old
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Course extends BaseCourse
{

    #####
    # Fetch
    ###

    /**
     * Get Doctrine Choice Option
     *
     * Select box choice course list for form.
     *
     * @return unknown
     */
    public function getDoctrineChoiceOption()
    {
        $max_len = 35;
        $name = $this->name;
        if (strlen($name) > $max_len) {
            $name = substr($name, 0, $max_len);
        }
        return $this->code.' - '.$name;
    }

    public function getCourseCategoryName() {
        return $this->category;
    }
    
    public function setUp(){
        parent::setUp();
        $this->hasMany('School', array(
             'refClass' => 'Department',
             'local' => 'school_id',
             'foreign' => 'school_id'));
    }
    
    public function getSchoolId() {
        $department = $this->getDepartment();
        $school = $department->getSchool();
        return $school->getName();
    }

    /**
     * Return department code - course code
     */
    public function getShortName(){

        $tabname = "";

        $tabname = $this->getCode();

        if ($this->getDepartment()) {
//            $tabname = substr($this->getDepartment()->getAlias(), 0, 5)." ".$this->getCode();
            $tabname = mb_substr($this->getDepartment()->getAlias(), 0, 5, 'utf-8')." ".$this->getCode();
        }

            if (!$this->getInstructor()) {
            $tabname = trim($this->getCategory());
            if (strlen($tabname) <= 0 || $tabname == 'NULL') {
                if ($this->getDepartment()) {
                    $tabname = $this->getDepartment()->getAlias()." ".$this->getCode();
                }
            }
        }
        if ($this->getInstructor() == $this->getName()) $tabname = $this->getCategory();

        if (strlen($tabname) <= 0) {
            $tabname = $this->getCode();
        }

        return substr($tabname, 0, 10);
    }

    /**
     * Get Students
     *
     * Get list of students for course.
     *
     * @return unknown
     */
    public function getStudents($limit = false)
    {
        $sql = Doctrine_Core::getTable('sfGuardUser')->createQuery('u')
            ->leftJoin('u.Courses c')
            ->where('c.id = ?', $this->id)
        ;

        if ($limit) {
            $sql->orderBy('RAND()')->limit($limit);
        } else {
            $sql->orderBy('u.last_name, u.first_name');
        }



        return $sql->execute();
    }


    #####
    # Boolean
    ###

    /**
     * Is Student
     *
     * Check to see if student is in the course.
     *
     * @param sfGuardUser $user
     * @return unknown
     */
    public function isStudent(sfGuardUser $user)
    {
        return in_array($this->id, $user->Courses->getPrimaryKeys());
    }
}
