<?php

/**
 * DepartmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepartmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Department');
    }

    /**
     * @param School|int $school
     * @param string $name
     * @return bool|Department
     */
    public function findOneBySchoolAndName($school, $name)
    {
        if ($school instanceof School) {
            $school = $school->getId();
        }

        $queryAlias = 'd';

        $name = trim($name);
        
        $match = $this->createQuery($queryAlias)
            ->where("$queryAlias.school_id = ?", $school)
            ->andWhere("$queryAlias.name like ?", $name);

        $matchSql = $match->buildSqlQuery();

        //using plain SQL because DQL does not support UNION
        $fullQuery = $matchSql . ' UNION ALL ' . $matchSql . ' UNION ALL ' . $matchSql . ' LIMIT 1';

        //prioritize exact match, then starts with, then contains
        $departmentArray = $this->getConnection()->fetchRow(
            $fullQuery,
            array($school, $name, $school, "$name%", $school, "%$name%")
        );

        //do some jank here to remove the table alias prefixes so we can hydrate the object
        if ($departmentArray) {
            $departmentKeys = array_keys($departmentArray);
            array_walk($departmentKeys, function(&$match) use ($queryAlias){
                $match = str_replace($queryAlias . '__', '', $match);
            });
            $departmentArray = array_combine($departmentKeys, array_values($departmentArray));
        }
        
        if (!empty($departmentArray)) {
            $department = new Department();
            $department->setArray($departmentArray);
            return $department;
        }
        return false;
    }
    
    /**
     * Get Departments By School Id SQL
     * 
     * Fetch the sql for departments for a given school.
     *
     * @param unknown_type $school_id
     * @return unknown
     */
    public static function getDepartmentsBySchoolIdSql($school_id)
    {
        $sql = self::getInstance()->createQuery('d')
            ->leftJoin('d.School s ON s.id=d.school_id')
            ->where('d.school_id = ?', $school_id)
            ->andWhere('s.is_lms = 0')
            ->orderBy('d.sort, d.name')
        ;
        return $sql;
    }    
    
    public function getSortByName() {
        $q = Doctrine_Query::create()
                ->select('d.id, d.name')
                ->from('Department d')
                ->orderBy('d.name');
        return $q->execute();
    }
}