<?php

/**
 * FriendRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox_old
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FriendRequest extends BaseFriendRequest
{
    
    const ACCEPTED_STATUS = 'accepted';
    const DECLINED_STATUS = 'declined';
    const PENDING_STATUS = 'pending';
    
}
