<?php

/**
 * FriendRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FriendRequestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FriendRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FriendRequest');
    }
}