<?php

/**
 * InstructorCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InstructorCourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InstructorCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InstructorCourse');
    }
    
    public function doSortInseructorList($query) {
        return $query->orderBy('user_id')->orderBy('course_id');
    }
    
}