<?php

/**
 * LinkDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkDataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LinkData');
    }
}