<?php

/**
 * LMSDomainKeySecretTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LMSDomainKeySecretTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LMSDomainKeySecretTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LMSDomainKeySecret');
    }
}