<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox_old
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Post extends BasePost
{
    const COURSE_OBJECT = 'Course';
    const NOTIFICATION_OBJECT = 'Notification';
    const SCHOOL_OBJECT = 'School';
    const SF_GUARD_USER_OBJECT = 'User';
    const USER_ATTACHMENT = 'UserAttachment';

    
    /**
     * Get post course if this post was written to a course object
     *
     * @return unknown
     */
    public function getCourse()
    {
        return $this->getObject() instanceof Course ? $this->getObject() : false;
    }    
    
    
    public function getNotification()
    {
        return $this->getObject() instanceof Notification ? $this->getObject() : false;
    } 
    
    public function getObject(){
        if($this->getObjectName()){
            return Doctrine_Core::getTable($this->getObjectName())->findOneById($this->getObjectId());

        }

        return false;
    }

    
    public function IsComment(){
        return $this->getParentPostId() ? true : false;
        
    }

}
