<?php

/**
 * SchoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SchoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SchoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('School');
    }
    
    
    public static function getClassYearChoices(){
        
        $years = array();
        $year = date('Y');
        
        for($i=0; $i <= 10; $i++){
            $years[$year+$i] = $year + $i;
        }
         
        return $years;
    }
    
    public function getSortByName() {
        $q = Doctrine_Query::create()
                ->from('School d')
                ->orderBy('d.name');
        return $q->execute();
    }
    
    public static function getNonLmsSchoolsSql()
    {
        $sql = self::getInstance()->createQuery('s')
            ->where('s.is_lms = 0')
            ->orderBy('s.name')
        ;
        return $sql;
    }   

}