<?php

/**
 * UserEventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserEventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserEventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserEvent');
    }
}