<?php

/**
 * UserCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserCourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserCourse');
    }
}