<?php

/**
 * UserTrackerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTrackerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserTrackerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserTracker');
    }
}