<?php

/**
 * UserAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserAttachmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserAttachment');
    }
}