<?php

/**
 * UserSchoolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSchoolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserSchoolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserSchool');
    }
}