<?php

/**
 * UserSubjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSubjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserSubjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserSubject');
    }
}