<?php

/**
 * UserLikeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserLikeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserLikeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserLike');
    }
}