generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Event
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          event_event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list: 
        display:
#          - course
          - name
#          - user
          - start_date
          - end_date
          - created_at
          - updated_at
          - deleted_at
      filter:
        display:
#          - course_id
          - name
#          - user_id

      form: 
        display:
          - name
          - start_date
          - end_date
      edit:    ~
      new:     ~
