generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        display:
          - first_name
          - last_name
          - email_address
          - is_active
          - is_staff
          - is_officer
          - number_of_course
          - is_super_admin
          - created_at
          - last_login
        title: User list
        table_method: doGetUserList

      filter:
        display:
          - first_name
          - last_name
          - email_address
          - is_active
          - is_staff
          - is_officer
      form:
        class: AdminSfGuardUserForm
      edit:
        title: Edit user
      new:
        title: New user
