all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=db.hq.endertech.net;dbname=wikigrads_v2
      username: username
      password: password
      attributes:
        use_native_enum: true
        use_dql_callbacks: true