generator:
  class: sfDoctrineGenerator
  param:
    model_class:           AcademicTerm
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          academic_term_academic_term
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  
        display:
          - term
          - year
          - is_active
      form:    ~
      edit:    ~
      new:     ~
