generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Department
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          department_department
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:
          - school
          - name
          - alias
          - updated_at
          - deleted_at
      filter:
        display:
          - school_id
          - name
          - alias
      form:
        display:
          - school_id
          - name
          - alias
          - sort
      edit:    ~
      new:     ~
