generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Subject
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          subject
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter: 
        display:
          - name
      form:
        display:
          - name
      edit:    ~
      new:     ~
